name:         CI

on:           [push]

jobs:
  build:

    runs-on:  ubuntu-latest

    steps:
    - uses:   actions/checkout@v1
    - name:   Build
      run:    make
    - name:   Clean
      run:    |
        make clean
